src/Observers/LogObserver.php
the 'logger' helper by default uses the 'debug' level. For that case, Laradumps will consider it the level log as info
=> fix when using 'logger()'

README.md
As the `Contributions` section has been removed from the `Readme` I am making this update.
Before
```html
<div align="center">
<h3> 
<a href="https://laradumps.gitbook.io/laradumps/">
📚 Documentation
</a>
<span> | </span>
<a href="https://github.com/laradumps/laradumps#contribution">
⌨️ Contribution
</a>
</h3>
</div>
```
After
```html
<div align="center">
<h3> 
<a href="https://laradumps.gitbook.io/laradumps/">
📚 Documentation
</a>
<span> | </span>
<a href="https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md">
⌨️ Contribution
</a>
</h3>
</div>
```
=> fix - Fixing Contributing Link on Readme Documentation File

src/LaraDumpsServiceProvider.php
This PR fixes the URL handler when ds is called via macro
=> Fix url handler from ds macro

src/Observers/LivewireObserver.php
This PR causes LaraDumps to send livewire requests to the Livewire screen
=> Send livewire components to Livewire screen

src/LaraDumps.php, src/Payloads/DiffPayload.php
Hi Luan,
As mentioned by Tio Jobs in his review, the parameter name `col` can be confusing.
I propose to rename it to `splitDiff`, as it controls whether the result will be split in two lines (original/diff).
Dan
=> Rename parameter to splitDiff

src/LaraDumps.php, src/Payloads/ValidateStringPayload.php
Hi Luan,
This PR adds the possibility to toggle `case sensitive` and `whole word` search in `ds()->contains()`.
**Motivation**
I believe in certain cases, a very permissive `contains()` could lead the user to false positives.
In the example below, the user would like to check for "Mariana" as a full word and not part of  "Marianatown".
```php 
$json = '{"name":"Paulo", "city":"Marianatown"}';
ds($json)->contains('Mariana'); //would produce ✅ Text contains
```
In languages like German, capitalizing nouns is important. `Elf` means the creature from folk stories, while `elf` means 11.
```php 
$json = '{"name":"Haleth", "nature":"Elf"}';
ds($json)->contains('elf'); //would produce ✅ Text contains
```
This PR introduces two parameters to control case sensitive and whole word search.
```php …
```
=> [1.0] Contains with case sensitive and whole word search

config/laradumps.php, src/Commands/CheckCommand.php, tests/CheckCommandTest.php
Hi Luan,
This PR enhances the `php artisan ds:check` and does not introduce any breaking change.
- The `dsq()` and `@dsAutoClearOnPageReload`  are now included in the functions to be checked;
- Commented  calls `//ds()` will produce now produce a  "ds() found error";
- Macro DS calls `User::query()->where('id', 20)->ds()->get();` also produces a  "ds() found error";
- Changed the `ci_check`.`directories` to  include only `base_path('app')` and ` base_path('resources')`;
- Removed the spaces on `ci_check`.`text_to_search` for better user experience;
- Test is now checking for functions; whenever  a new shortcut is created, it must be included there.
Currently, `ds:check` is not detecting the commented calls and macro calls.
Even though commented `ds()` calls would  not produce any problem, …
=> Enhance ds:check for dsq, ds-macro, commented ds and dsAutoClearOnPageReload directive

src/Observers/LivewireFailedValidationObserver.php
Hey, @luanfreitasdev 
Laradumps was ignoring the user's livewire failed validation config.
I added the check that was missing and removed some class imports that were not being used.
=> Fix application showing livewire failed validation even disabled in settings

config/laradumps.php
- Removed some extra spaces
```diff
- |  IDE Handlers
+ | IDE Handlers 
```
- I broke some lines, which were longer than 80 characters.
```diff
-    | Set auto_clear_on_page_reload to true so LaraDumps will clear history automatically on page reload.
+    | Set auto_clear_on_page_reload to true so LaraDumps will clear history
+    | automatically on page reload.
```
- I put an empty line, around the comments
```diff
- return [
-     /*
+ return [
+
+     /*
```
And some other small tweaks
=> Fix config file 

config/laradumps.php, src/Support/IdeHandle.php
Now, we fixed it adding new .env variables and fixing the replace on IdeHandle.php file.
**Follow the image:**
**New variable added:**
**Replacing on IdeHandle.php:**
**laradumps.php (config):**
=> hotfix: fixed handle click on LaraDumps

src/Commands/InitCommand.php, tests/InitCommandTest.php
Hi Luan,
This PR has no breaking changes, and it introduces small improvements:
`  ➕ `  Added the question for `DS_LIVEWIRE_EVENTS` in accordance to PR https://github.com/laradumps/laradumps/pull/39
---
---
_When choosing "vscode_remote", the user will be informed that extra configuration is needed._
---
Please let me know if changes are required.
Dan
=> Improvements ds:init (config file delete and IDEs from package config) & Livewire Events

.github/workflows/php.yml, .php-cs-fixer.php
Hi Luan,
This PR adds Windows and MacOS to GitHub Actions and does not introduce breaking changes.
Users might be developing Laravel applications from Linux, macOS and Windows operating systems, so I believe it is beneficial to test the package in each of them.
<p align="center">
</p>
Dan
=> Adds Windows and macOS to GitHub Actions 

src/LaraDumps.php, src/Payloads/Payload.php, src/Payloads/TimeTrackPayload.php
Hi Luan,
This PR introduces the feature `ds()->time()` which allows the user to wrap a piece of code and clock the execution time.
It is paired with the PR https://github.com/laradumps/app/pull/62.
Developers often make use of the `microtime()` approach to simply clock the execution time of a particular block of code.
Even though there are (better) alternatives to this approach, I believe having it as a method adds a convenient way, and a shortcut, for those who end up writing the entire code and passing to a `ds()` call.
The user must wrap a piece of code with `ds()->time($reference)` and `ds()->stopTime($reference)`. 
The `$reference` must be a unique identifier and be the same, both in `time()` and `stopTime()`. This string can be a simple word or a short phrase, and it will also be …
=> Feature: Time Tracker

src/Actions/ConsoleUrl.php, src/Commands/InitCommand.php, tests/InitCommandTest.php
Hi Luan,
This PR includes an enhancement to `artisan ds:init()` command, small improvements and a bug fix. 
Currently, we have two key points that require the user to read the documents to properly configure LaraDumps: `docker + linux` and `vscode remote`.
Now, whenever these options are selected, the user will be prompted to browse the documentation (`default: no`). This question improves the odds of users seeing this alert instead be carried with the output flow and thus be frustrated because things don't work.
The question `Allow dumping Livewire Events & Browser Events (dispatch) to the App?` will now enable/disable both event functionalities.
In the video [Como contribuir em projetos open source PHP ou Laravel? ](https://www.youtube.com/watch?v=8KsHhQ6GcBg) @icarojobs experienced an …
=> [1.2] Enhancement URL in ds:init + bug fix

src/Actions/SendPayload.php, src/Exceptions/CannotSendPayloadException.php, src/LaraDumps.php, tests/TestCase.php
While installing LaraDumps to debug the development of a Laravel Package, I noticed the following error:
My Laravel package does not have Guzzle installed.
One alternative would be to require `guzzlehttp/guzzle` with LaraDumps or even with the package-dev, but I questioned myself if it makes sense to add a dependency to only make a single post request. …
=> Refactored HTTP into Action to remove dependency

.github/workflows/php.yml, phpstan.neon.dist
This Pull Request is a work in progress, and fix deprecated GitHub actions seen in Annotations on this [run](https://github.com/laradumps/laradumps/actions/runs/3259434554).
I am not certain why we still have the annotation `The 'set-output' command is deprecated and will be disabled soon.` since `echo "::set-output` calls were removed.
=> [Fix] Update CI Deprecations

src/Actions/GitDirtyFiles.php, src/Commands/CheckCommand.php
This PR allows _ds:check_ to parse files that have not yet been committed to git when using `--dirty ` as a parameter.
**intended for use only in the commit-msg hook or for quick query**
```bash
php artisan ds:check --dirty
```
This code snippet was taken from laravel pint #https://github.com/laravel/pint/pull/130
=> ds:check --dirty

src/LaraDumpsServiceProvider.php, tests/PayloadTest.php
Added 2 macros:
- Illuminate\Support\Stringable;
- Illuminate\Support\Collection;
This Pull Request adds two new Macros
- Illuminate\Support\Collection;
``` collect(['abc', 'xyz'])->ds('original')->map(function($c) { return ucfirst($c); })->ds('modified'); ```
- Illuminate\Support\Stringable;
``` Str::of('ABC')->append(' …
```
=> Added Stringable & Collection macro;

.github/workflows/check_vardump.yml
`  🗒️  `  Please read the [Contributing Guide](https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md) and follow all steps listed there.
`  ✍️  `  Give this PR a meaningful title.
`  📣  `  Describe your PR details below.
This Pull Request introduces a new GitHub action to check if there are any forgotten/left-over var dump functions.
After the fix in https://github.com/laradumps/laradumps/pull/84 removing residual `logger()` function, I have decided to reduce the possibility of this happening again.
This action uses the package `php-parallel-lint/PHP-Var-Dump-Check`, passing …
=> [Pipeline] Checking for forgotten var dump functions

src/LaraDumps.php, src/Support/Dumper.php
`  🗒️ `  Please read the [Contributing Guide](https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md) and follow all steps listed there.
`  ✍️ `  Give this PR a meaningful title.
`  📣 `  Describe your PR details below.
This PR Fixes the Issue https://github.com/laradumps/laradumps/issues/97
This Pull Request solves the issue with values not being displayed.
While using the demo code provided in the issue, I thought it could be helpful to show types.
Currently, it is not clear if the dump value is `'0'` or `0`.
```php
ds('');
ds(null);
ds('0');
ds(0);
ds(0.1);
```
With this PR, …
=> [Fix] "Values are not being displayed"

src/LaraDumpsServiceProvider.php
Hello,
I noticed a "permission denied" when trying to require the functions file on PHP 8.2 Windows, where there was no issues with PHP 8.1
=> Fix the require './functions' which broke on PHP 8.2 Win

src/Actions/GitDirtyFiles.php
Often we are working with many files, so when I have the file A and B, but in the file B I have a dd or ds and in the file A i don't  and i want to make a commit just with the file A changes. The check dirt blocks my commit because of the file B. But the file A is correct and is the just one i want to make a commit.
This Pull Request adds a check constraint that will just consider the check dirty for the "staged changes files", checking only the files i want to use for that specific commit.
=> check dirty only on stashed changes
