laradumps/laradumps

src/LaraDumps.php
src/LaraDumpsServiceProvider.php
src/Observers/QueryObserver.php
src/Payloads/BladePayload.php
src/Support/IdeHandle.php
src/functions.php
tests/PayloadTest.php

This PR Fix URL handler from blade directive.

Fix Blade directive url handler

---

src/Commands/InitCommand.php
tests/InitCommandTest.php

Hi Luan,
This PR adds the `Livewire Validation` and `Livewire Auto-clear` to the `artisan ds:init`.
Dan

[1.0] Update ds:init with Livewire Validation and Livewire Auto-clear

---

README.md

Hi Luan,
Updating README for 1.0
- Links
- Features

[1.0] Readme update

---

src/LaraDumpsServiceProvider.php

Fix dsAutoClearOnPageReload

---

config/laradumps.php

Hi Luan,
Reviewing and reorganizing the config file.
Dan

Reorganize the Config

---

composer.lock
src/LaraDumpsServiceProvider.php
src/Observers/LivewireComponentsObserver.php
src/Observers/LivewireDispatchObserver.php
src/Observers/LivewireEventsObserver.php

This PR fixes opening the files when firing a /dispatch event and removes the text App\Http\Livewire

Fix events and dispatch ide-handler

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
tests/TestCase.php

GitHub templates

---

src/Observers/LivewireComponentsObserver.php

Fix static analysis
```plain
------ ----------------------------------------------------------------------- 
Line   Observers/LivewireComponentsObserver.php                               
------ ----------------------------------------------------------------------- 
25     Parameter #2 $needles of static method                                 
Illuminate\Support\Str::contains() expects                             
(Illuminate\Support\Enumerable<(int|string), …
```

[Fix] Static analysis on LivewireComponentsObserver

---

resources/js/index.js

This PR fixes the env import when using VITE.

Fixes the env import when using VITE

---

composer.lock
config/laradumps.php
src/Concerns/Colors.php
src/Observers/LogObserver.php

Add all Logs to one screen

---

src/LaraDumps.php
src/Payloads/CoffeePayload.php
src/Payloads/Payload.php

This Pull Request adds a very useful tool for debugging code on Fridays: Sense of humor 😁

[FEATURE] ☕ Have a coffeee

---

config/laradumps.php
src/Actions/OpenLaraDumps.php
src/Actions/SendPayload.php
src/Commands/OpenLaraDumpsCommand.php
src/LaraDumps.php
src/LaraDumpsServiceProvider.php

This PR makes it possible to automatically open the application when we call a `"ds()"` via browser but the application was not yet open.
Can be negated in config by making '`false`' in `auto_start_with_deeplink`

[Feature] Allow to open app automatically

---

composer.lock
config/laradumps.php
src/LaraDumps.php
src/LaraDumpsServiceProvider.php
src/Observers/LivewireFailedValidationObserver.php
src/Observers/LogObserver.php
src/Observers/QueryObserver.php
src/Payloads/Payload.php
src/Payloads/QueryPayload.php
src/Support/IdeHandle.php
src/functions.php
tests/PayloadTest.php

https://github.com/laradumps/app/pull/127
This Pr makes it possible to remove the sql formatting, show or not the connection information via config when we hear queries from laravel.
```php
'send_queries' => [
'enabled' => env('DS_SEND_QUERIES', false),
'formatted' => false,
'show_connection_information' => false,
]
```

Refactoring query observer

---

src/LaraDumps.php
src/LaraDumpsServiceProvider.php
src/Payloads/Payload.php
src/Support/Dumper.php
src/Support/IdeHandle.php
tests/PayloadTest.php

Revert commit v2

---

src/Actions/OpenLaraDumps.php

Fix message when using livewire

---

src/Commands/CheckCommand.php

This PR fixes --dirty when it has no files

Fix bug when not is dirty

---

src/LaraDumps.php
src/Payloads/MarkdownPayload.php
tests/PayloadTest.php

This Pull Request adds Markdown payload that dump rendered markdown
```
ds()->markdown('# Hi, Anand Pilania!');
```

Added MarkdownPayload;

---

.github/workflows/php.yml
composer.lock
config/laradumps.php
larastan.sh
src/LaraDumpsServiceProvider.php
src/Observers/HttpClientObserver.php
src/Observers/LivewireDispatchObserver.php
src/Observers/LivewireEventsObserver.php
src/Payloads/Payload.php
src/Payloads/PhpInfoPayload.php
src/Payloads/RoutesPayload.php
tests/InitCommandTest.php

📌 Fixed the ds:init test to make sure it runs on order by random when running tests
📌 Fixed the file path for functions.php in LaraDumpsServiceProvider.php to allow including it when using Windows
📌  CS Fixer only runs on LINUX (excluding: macOS and Windows)
📌 Modified the CI to use the composer script commands instead of running the binaries.
📌  Larastan is hard-coded to run on 9x and 10x in php.yml
📌 Removed larastan.sh in favor of using "if" in github actions
This PR requires …

[2x Fix] CI failing code style; fix ds:init test; remove larastan.sh

---

src/LaraDumps.php

This PR names some methods to make it easier we call
```php
->httpClientOn -> httpOn
->showCache -> cacheOn
->showJobs -> jobsOn
```

Rename jobs, cache and http

---

composer.lock
config/laradumps.php
src/Concerns/Traceable.php
src/Observers/CacheObserver.php
src/Observers/JobsObserver.php
src/Observers/QueryObserver.php

Fix cache Observer

---

src/Observers/CacheObserver.php

- [ X] Bug fix
This Pull Request remove the logger from CacheObserver causing a lot of logs on the application.
- [X ] I have read and followed the steps listed in the [Contributing Guide](https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md).
- [X ] No

Remove logger from CacheObserver

---

src/Observers/CommandObserver.php

Fix command observer enabled bug

---

src/Observers/JobsObserver.php

Disable JobObserver by default

Disable JobsObserver

---

src/LaraDumps.php
src/Payloads/BenchmarkPayload.php

This pull request introduces a new `BenchmarkPayload` class that provides a simple way to benchmark closures and dump detailed results to the App. The class takes an array of closures or a variable number of closures as arguments, and benchmarks each of them in turn, dumping results as TableV2 that includes start time, end …

added Benchmark Payload

---

src/Observers/QueryObserver.php

QueryObserver: Object of class DateTime could not be converted to string

---

src/LaraDumps.php
src/Payloads/BenchmarkPayload.php
src/Support/Dumper.php

This Pull Request extends Benchmark to Eloquent & Query Builders and Collection.
Enable as:
```
ds()->benchmarkUseAs()
->collectionMacro() // FOR Collection
->eloquentMacro() // FOR Eloquent
->queryBuilderMacro(); // FOR Query Builder
```
Use as:
Eloquent
```
\App\Models\User::where('id', '1')
->benchmark([
'a' => function($b) …
```

extending BenchmarkPayload to Collection/Eloquent & Query Builder;

---

src/Actions/SendPayload.php
tests/SendPayloadTest.php
tests/TestCase.php

This PR fixes slow page loading when the app is off but sendings are enabled.

Fix slow loading when the app is off
